name: NodeJS-to-Azure CI/CD

on:
  workflow_run:
    workflows: ["NodeJS CI"]
    branches: [main]
    types: [completed]
  
env:
  NODE_VERSION: '14.x'

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@main
      
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and Push Image to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/imageresizer:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/imageresizer:${{ github.sha }}


  deploy-to-aci:
    name: Deploy to ACI 
    runs-on: ubuntu-latest
    needs: build-container-image
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@main
      
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/imageresizer:${{ github.sha }}
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: aci-imageresizer
        location: 'norwayeast'

    - name: Azure logout
      run: |
        az logout
